import { chmod, copyFile, mkdir, readdir, writeFile } from "node:fs/promises";
import { basename, extname, resolve } from "node:path";
import type { WikiConfig } from "./config";

export interface GeneratedProject {
  directory: string;
  logoFilename?: string;
}

const phpQuote = (value: string): string => value.replaceAll("\\", "\\\\").replaceAll("'", "\\'");

function renderCompose(config: WikiConfig): string {
  return `services:
  database:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: mediawiki
      MARIADB_USER: mediawiki
      MARIADB_PASSWORD: \${DATABASE_PASSWORD}
      MARIADB_ROOT_PASSWORD: \${DATABASE_ROOT_PASSWORD}
    volumes:
      - database-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 20

  mediawiki:
    image: mediawiki:1.46.0
    restart: unless-stopped
    ports:
      - "\${WIKI_PORT}:80"
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - wiki-data:/var/www/html
      - ./data/images:/var/www/html/images
      - ./LocalSettings.autosetup.php:/var/www/html/LocalSettings.autosetup.php:ro

volumes:
  database-data:
  wiki-data:
`;
}

function renderEnvironment(config: WikiConfig): string {
  return [
    `WIKI_PORT=${config.port}`,
    `WIKI_NAME=${config.wikiName}`,
    `WIKI_LANGUAGE=${config.language}`,
    `WIKI_URL=${config.siteUrl}`,
    `WIKI_ADMIN=${config.adminUser}`,
    `WIKI_ADMIN_PASSWORD=${config.adminPassword}`,
    `DATABASE_PASSWORD=${config.databasePassword}`,
    `DATABASE_ROOT_PASSWORD=${crypto.randomUUID().replaceAll("-", "")}`,
    "",
  ].join("\n");
}

function renderSettings(config: WikiConfig, logoFilename?: string): string {
  const url = new URL(config.siteUrl);
  const scriptPath = url.pathname === "/" ? "" : url.pathname.replace(/\/$/, "");
  const extensions = config.extensions.map((name) => `wfLoadExtension( '${phpQuote(name)}' );`).join("\n");
  const logo = logoFilename
    ? `\n$wgLogos = [ '1x' => "$wgScriptPath/images/${phpQuote(logoFilename)}" ];`
    : "";

  return `<?php
// Generated by MediaWiki Autosetup. Safe to customize after installation.
$wgSitename = '${phpQuote(config.wikiName)}';
$wgServer = '${phpQuote(url.origin)}';
$wgScriptPath = '${phpQuote(scriptPath)}';
$wgEnableUploads = true;
$wgUseInstantCommons = true;
$wgEmergencyContact = 'admin@localhost';
$wgPasswordSender = 'admin@localhost';
${logo}

// Selected bundled extensions
${extensions}
`;
}

function renderReadme(config: WikiConfig): string {
  return `# ${config.wikiName}

Generated by MediaWiki Autosetup.

## Start and stop

\`\`\`sh
docker compose up -d
docker compose down
\`\`\`

Open ${config.siteUrl} after the installation completes.

Configuration secrets are stored in \`.env\`. Keep that file private and back up both Docker volumes regularly.
`;
}

export async function generateProject(config: WikiConfig): Promise<GeneratedProject> {
  const directory = resolve(config.outputDirectory);
  await mkdir(directory, { recursive: true });
  const existing = await readdir(directory);
  if (existing.length > 0) throw new Error(`The output directory is not empty: ${directory}`);

  await mkdir(resolve(directory, "data/images"), { recursive: true });
  await chmod(resolve(directory, "data/images"), 0o777);
  let logoFilename: string | undefined;
  if (config.logoPath) {
    const suffix = extname(config.logoPath).toLowerCase() || ".png";
    logoFilename = `wiki-logo${suffix}`;
    await copyFile(resolve(config.logoPath), resolve(directory, "data/images", logoFilename));
  }

  await Promise.all([
    writeFile(resolve(directory, "compose.yml"), renderCompose(config)),
    writeFile(resolve(directory, ".env"), renderEnvironment(config), { mode: 0o600 }),
    writeFile(resolve(directory, "LocalSettings.autosetup.php"), renderSettings(config, logoFilename)),
    writeFile(resolve(directory, ".gitignore"), ".env\ndata/\n"),
    writeFile(resolve(directory, "README.md"), renderReadme(config)),
  ]);

  return { directory, logoFilename };
}

export const templates = { renderCompose, renderEnvironment, renderSettings };
 
