import { chmod, copyFile, mkdir, readdir, writeFile } from "node:fs/promises";
import { extname, resolve } from "node:path";
import {
  CAP_CAPTCHA_AUTHENTICATION_REQUEST,
  CAP_CAPTCHA_CLASS,
  CAP_CAPTCHA_FIELD,
  CAP_EXTENSION_MANIFEST,
  captchaEnvironmentVariables,
  renderCaptchaSettings,
} from "./captcha";
import type { WikiConfig } from "./config";

export interface GeneratedProject {
  directory: string;
  logoFilename?: string;
}

const phpQuote = (value: string): string => value.replaceAll("\\", "\\\\").replaceAll("'", "\\'");

function renderCompose(config: WikiConfig): string {
  const captchaVariables = captchaEnvironmentVariables(config.captcha);
  const captchaEnvironment = captchaVariables.length > 0
    ? `    environment:\n${captchaVariables.map(([name]) => `      ${name}: \${${name}}`).join("\n")}\n`
    : "";
  const captchaVolume = config.captcha.provider === "cap"
    ? "      - ./extensions/CapCaptcha:/var/www/html/extensions/CapCaptcha:ro\n"
    : "";
  return `services:
  database:
    image: mariadb:11.4
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: mediawiki
      MARIADB_USER: mediawiki
      MARIADB_PASSWORD: \${DATABASE_PASSWORD}
      MARIADB_ROOT_PASSWORD: \${DATABASE_ROOT_PASSWORD}
    volumes:
      - database-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 20

  mediawiki:
    image: mediawiki:1.46.0
    restart: unless-stopped
    ports:
      - "\${WIKI_PORT}:80"
    depends_on:
      database:
        condition: service_healthy
${captchaEnvironment}
    volumes:
      - wiki-data:/var/www/html
      - ./data/images:/var/www/html/images
      - ./LocalSettings.autosetup.php:/var/www/html/LocalSettings.autosetup.php:ro
${captchaVolume}

volumes:
  database-data:
  wiki-data:
`;
}

const dotenvQuote = (value: string | number): string => `'${String(value).replaceAll("'", "\\'")}'`;

function renderEnvironment(config: WikiConfig): string {
  const values = [
    `WIKI_PORT=${dotenvQuote(config.port)}`,
    `WIKI_NAME=${dotenvQuote(config.wikiName)}`,
    `WIKI_LANGUAGE=${dotenvQuote(config.language)}`,
    `WIKI_URL=${dotenvQuote(config.siteUrl)}`,
    `WIKI_ADMIN=${dotenvQuote(config.adminUser)}`,
    `WIKI_ADMIN_PASSWORD=${dotenvQuote(config.adminPassword)}`,
    `DATABASE_PASSWORD=${dotenvQuote(config.databasePassword)}`,
    `DATABASE_ROOT_PASSWORD=${dotenvQuote(crypto.randomUUID().replaceAll("-", ""))}`,
  ];
  for (const [name, value] of captchaEnvironmentVariables(config.captcha)) {
    values.push(`${name}=${dotenvQuote(value)}`);
  }
  return [...values, ""].join("\n");
}

function renderSettings(config: WikiConfig, logoFilename?: string): string {
  const url = new URL(config.siteUrl);
  const scriptPath = url.pathname === "/" ? "" : url.pathname.replace(/\/$/, "");
  const extensions = config.extensions.map((name) => `wfLoadExtension( '${phpQuote(name)}' );`).join("\n");
  const logo = logoFilename
    ? `\n$wgLogos = [ '1x' => "$wgScriptPath/images/${phpQuote(logoFilename)}" ];`
    : "";

  return `<?php
// Generated by MediaWiki Autosetup. Safe to customize after installation.
$wgSitename = '${phpQuote(config.wikiName)}';
$wgServer = '${phpQuote(url.origin)}';
$wgScriptPath = '${phpQuote(scriptPath)}';
$wgEnableUploads = true;
$wgUseInstantCommons = true;
$wgEmergencyContact = 'admin@localhost';
$wgPasswordSender = 'admin@localhost';
${logo}

// Selected bundled extensions
${extensions}
${renderCaptchaSettings(config.captcha)}
`;
}

function renderCaptchaReadme(config: WikiConfig): string {
  switch (config.captcha.provider) {
    case "cap":
      return `
## Cap CAPTCHA

This wiki uses the self-hosted [Cap CAPTCHA](https://github.com/tiagozip/cap). Keep the Cap asset server enabled and publicly reachable at ${config.captcha.serverUrl}. In the Cap dashboard, allow ${config.siteUrl} as a CORS origin.

Pin the Cap asset server to \`WIDGET_VERSION=0.1.56\` and \`WASM_VERSION=0.0.7\`.

The site secret is stored only in \`.env\`; never paste it into logs or issue reports.
`;
    case "turnstile":
      return `
## Cloudflare Turnstile

This wiki uses Cloudflare Turnstile through MediaWiki's bundled ConfirmEdit extension. Register the visitor-facing hostname for ${config.siteUrl} in the Cloudflare Turnstile dashboard.

The secret key is stored only in \`.env\`; never paste it into logs or issue reports.
`;
    case "hcaptcha":
      return `
## hCaptcha

This wiki uses hCaptcha through MediaWiki's bundled ConfirmEdit extension. Register the visitor-facing hostname for ${config.siteUrl} in the hCaptcha dashboard.

The secret key is stored only in \`.env\`; never paste it into logs or issue reports.
`;
    case "recaptcha":
      return `
## Google reCAPTCHA v2

This wiki uses Google reCAPTCHA v2 through MediaWiki's bundled ConfirmEdit extension. Register the visitor-facing hostname for ${config.siteUrl} in the Google reCAPTCHA admin console.

The secret key is stored only in \`.env\`; never paste it into logs or issue reports.
`;
    case "none":
      return "";
  }
}

function renderReadme(config: WikiConfig): string {
  return `# ${config.wikiName}

Generated by MediaWiki Autosetup.

## Start and stop

\`\`\`sh
docker compose up -d
docker compose down
\`\`\`

Open ${config.siteUrl} after the installation completes.

Configuration secrets are stored in \`.env\`. Keep that file private and back up both Docker volumes regularly.
${renderCaptchaReadme(config)}
`;
}

export async function generateProject(config: WikiConfig): Promise<GeneratedProject> {
  const directory = resolve(config.outputDirectory);
  await mkdir(directory, { recursive: true });
  const existing = await readdir(directory);
  if (existing.length > 0) throw new Error(`The output directory is not empty: ${directory}`);

  await mkdir(resolve(directory, "data/images"), { recursive: true });
  await chmod(resolve(directory, "data/images"), 0o777);
  let logoFilename: string | undefined;
  if (config.logoPath) {
    const suffix = extname(config.logoPath).toLowerCase() || ".png";
    logoFilename = `wiki-logo${suffix}`;
    await copyFile(resolve(config.logoPath), resolve(directory, "data/images", logoFilename));
  }

  if (config.captcha.provider === "cap") {
    await mkdir(resolve(directory, "extensions/CapCaptcha/includes"), { recursive: true });
  }

  await Promise.all([
    writeFile(resolve(directory, "compose.yml"), renderCompose(config)),
    writeFile(resolve(directory, ".env"), renderEnvironment(config), { mode: 0o600 }),
    writeFile(resolve(directory, "LocalSettings.autosetup.php"), renderSettings(config, logoFilename)),
    writeFile(resolve(directory, ".gitignore"), ".env\ndata/\n"),
    writeFile(resolve(directory, "README.md"), renderReadme(config)),
    ...(config.captcha.provider === "cap" ? [
      writeFile(resolve(directory, "extensions/CapCaptcha/extension.json"), CAP_EXTENSION_MANIFEST),
      writeFile(resolve(directory, "extensions/CapCaptcha/includes/CapCaptcha.php"), CAP_CAPTCHA_CLASS),
      writeFile(
        resolve(directory, "extensions/CapCaptcha/includes/CapCaptchaAuthenticationRequest.php"),
        CAP_CAPTCHA_AUTHENTICATION_REQUEST,
      ),
      writeFile(resolve(directory, "extensions/CapCaptcha/includes/HTMLCapCaptchaField.php"), CAP_CAPTCHA_FIELD),
    ] : []),
  ]);

  return { directory, logoFilename };
}

export const templates = { renderCompose, renderEnvironment, renderSettings };
 
